export interface SecondaryProposalModelInterface {
    id: number,
    lock_tx_hash:string,
    unlock_tx_hash:string,
    lock_blockchain_status:string,
    unlock_blockchain_status:string,   
    approval_tx_hash:string,
    coin_family:number,
    cancelled_status:number,
    is_cancelled:number,
    coin_id:number,
    user_id?: number,
    proposal_id?: number | 0,
    seller_wallet_address: string,
    secondary_market_proposal_id: number,
    raise_fund: string,
    collected_fund: string,
    token_values: string,
    token_quantity: string,
    token_to_sold: string,
    blocked_tokens: number,
    status: string,
    token_address: string | null,
    created_at?: string,
    updated_at?: string,
}