export interface ProposalInterface {
    id: number,
    title?: string,
    description?: string,
    company_name: string,
    token_name: string,
    raise_fund: string,
    collected_fund: string,
    token_address: string | null,
    fee?: string,
    project_id: number,
    agent_address: string | null,
    start_date?: string,
    end_date: string,
    min_investment: string,
    token_to_sold: string,
    minted_token_quantity:string,
    blocked_tokens: number,
    unique_id: string,
    token_quantity: string,
    symbol: string,
    project_yield: string,
    asset_info: string,
    mint_status: number,
    status: number,
    soft_cap_status: number,
    hard_cap_status: number,
    relisted: number,
    asset_type_id: number,
    token_id: string,
    created_at?: string,
    updated_at?: string,
}